### ISSUE TITLE
Perhaps partially obsolete?

### ISSUE THREAD

**Issue by SteveClement** [mokaddem/PyMISP-wrapper#3]
I wonder if this: https://github.com/MISP/PyMISP/tree/master/examples/feed-generator-from-redis would be where some of this code ended up in?

**Comment by mokaddem** [comment]
Oh wow. Completely forgot about this repository oO.
Indeed, the ``feed-generator-from-redis`` partially contain the code.
I'll see I should delete this repository or maintain it.
Thanks for the nudge! ;)
